### ISSUE TITLE
Waiting with several outcomes

### ISSUE THREAD

**Issue by alexhanh** [watir/watir-webdriver#334]
Working with a website where several different outcomes are possible as a result of an AJAX call. Unfortunately, the outcomes don't share a common structure. It seems `wait_until_present` and `when_present` fall down in this case, because they don't support waiting for one of multiple possibilities (essentially an `OR` operator).

Is there a neat Watir way to solve this that I've overlooked? Right now, I'm thinking of using a simple polling solution. I could imagine an `AND` operator being useful sometimes as well:

```ruby
def wait_until_any_present(elements*)
  Watir::Wait.until { elements.any? { |e| e.present? } }
end

def when_any_present(elements*)
  if block_given?
    start = Time.now
    loop do
      result = elements.find { |e| e.present? }
      yield result if result

      sleep Watir::Wait::INTERVAL
      raise Watir::Wait::TimeoutError if Time.now - start > Watir.default_timeout
    end
  else
    # TODO: WhenPresentDecorator doesn't seem to work in this case
  end
end

def wait_until_all_present(elements*); end

def when_all_present(elements*); end

# Example usage
modal = browser.div(id: 'modal')
flash = browser.span(id: 'flash', text: /Server error/)

wait_until_any_present(modal, flash)

when_any_present(modal, flash) do |element|
  case element.id
  when 'modal'
  when 'flash'
  else
  end
end
```

There might be a more elegant way to achieve this by defining the callbacks directly to the elements (would get rid of the checking in the callback block above).
Unfortunately, I'm not too familiar with event/callback oriented progamming, so I just don't know how to implement that kind of flow elegantly. Here's an example of the usage in this case:

```ruby
when_any_present(modal => Proc.new { |modal| ... }, flash => Proc.new { |flash| ... })
# or maybe (not sure if this even works)
when_any_present(modal, flash) do |modal, flash|
  modal do |m|
  end

  flash do |f|
  end
end
# or maybe
modal_future = modal.found do |result|
end

flash_future = flash.found do |result|
end

when_any_present(modal_future, flash_future)
```

How have you guys solved this? Would something like this be useful in Watir?

**Comment by titusfortner** [comment]
Thank you for submitting your ideas. I use a couple of these patterns in my tests as well. 

For the #wait_until_all_present case, I just put them sequentially. This has the added advantage of giving you the selector string of the element that doesn't show up in the error message if it fails, instead of just a timeout error:
```
element1.wait_until_present
element2.wait_until_present
element3.wait_until_present
```

For the #wait_until_any_present case, I don't see much advantage to abstracting it out for a single line of code.

The existing #when_present pattern exists to take a further action on a given element after it is present, whereas your #when_any_present method takes an action based on a conditional pattern and therefore isn't congruous. (and I'm not a fan of conditional actions based on website state in general, but that's another discussion for another time).

Regardless, since your method suggestions take elements as parameters instead of acting on an element object directly, they don't belong in the Watir project directly at this time. They are better suited to some kind of helper method module or the like for you to namespace as you need in your tests.

Please continue to send ideas for how this project can be made more useful to you.
