### ISSUE TITLE
Watir::Wait#until no longer returns result of block

### ISSUE THREAD

**Issue by chrismikehogan** [watir/watir-webdriver#360]
This commit (https://github.com/watir/watir-webdriver/commit/4399432733b78bddf07ceebaeda44ad0d17a05cb) changed how `Wait#until` returns.

We have some code that enjoyed the old behavior, where #until would return the result of the block. Was the change to have it always return `true` intentional?

**Comment by p0deje** [comment]
That was just a result of refactoring. There is no specific reason not to return result of block so we can easily return it, but why do you need it?

**Comment by chrismikehogan** [comment]
It's been convenient when waiting for truthy things that are not watir elements. For example in contexts where we have to deal directly with the Selenium element.

**Comment by chrismikehogan** [comment]
I'm unclear as to the process for adding specs to watirspec. Do I have to fork watirspec and make PR there with the additional tests?

**Comment by bret** [comment]
@chrismikehogan yes please go ahead and add a spec for the legacy behavior to a fork of watirspec and make a pull request. It would also be great if you submitted a pull request that restored the legacy behavior to Watir::Wait#until.

**Comment by chrismikehogan** [comment]
Thanks @bret. That PR is here https://github.com/watir/watir-webdriver/pull/362 (and failing tests b/c of my bad watirspec update)

**Comment by chrismikehogan** [comment]
PR's into watir-webdriver and watirspec made. I amended watir-webdriver PR so it doesn't include the watirspec update. Figured that would come after the watirspec PR is accepted.

**Comment by titusfortner** [comment]
Can you give an example of how this is actually being used? Philosophically I agree with the refactor. Procedure methods are executed for their effect, whereas functional methods are executed for their return value. Scala and Haskell go so far as to return nil for all such procedural methods to explicitly prevent what you are suggesting. I see this in a very similar light as the disagreements in the Rails community over predicate methods only returning true/false in line with the intent of the method name instead of returning a truthy value that includes additional useful information. Best practice is to never write code that relies on how it is implemented. The refactored wait method fulfills its contract to wait.

**Comment by bret** [comment]
Titus,

To me the key thing is that we strive to provide backwards compatibility,
unless we have a specific and compelling reason not to.

Your reflections bear on the design of new methods, which is something else.

Bret

**Comment by chrismikehogan** [comment]
@titusfortner yea I agree we shouldn't have used it in this way, and we wont be going forward. But we did. And we have paid the price. 

Thanks the help all.
