### ISSUE TITLE
href.baseVal unsupported?

### ISSUE THREAD

**Issue by bootstraponline** [watir/watir-webdriver#364]
Given this html:
```html
<i class="svg-icon" name="download-button">
<svg>
<use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="https://example/test"></use>
</svg>
</i>
```

Is execute_script the only way to get the href?

```ruby
> ele = browser.element(css: 'i[name="download-button"] svg use')
=> #<Watir::HTMLElement:0x..f97a6669a50b71f38 located=false selector={:css=>"i[name=\"download-button\"] svg use"}>

> browser.execute_script('return arguments[0].href.baseVal', ele)
=> "https://example/test"

> ele.locate.attribute('href')
=> nil

> ele.locate.attribute('baseVal')
=> nil
```

**Comment by titusfortner** [comment]
Try #attribute_value instead of #attribute, https://github.com/watir/watir-webdriver/blob/master/lib/watir-webdriver/elements/element.rb#L270

Also, questions like this often get better responses on stack overflow or our email list - http://groups.google.com/group/watir-general

**Comment by bootstraponline** [comment]
```
> ele.attribute_value 'href'
=> nil
> ele.attribute_value 'baseVal'
=> nil
```

Is the google group the best place to track defects?

**Comment by p0deje** [comment]
That is actually a question for selenium team, because watir-webdriver simply proxies attribute retrieval to selenium-webdriver.

Still, the reason you can't retrieve attribute is because calling `#attribute_value` is similar to `.getAttribute()` in JavaScript, which returns the text attribute of HTML tag (always string), not DOM element attribute. Compare:

```javascript
el = document.getElementsByTagName('use')[0]
el.href
// SVGAnimatedString { baseVal: "https://example/test", animVal: "https://example/test" }
el.getAttribute('href')
// null
```

Since your HTML element doesn't have `href` attribute, it's empty. However, your HTML element has `xlink:href`, so you can retrieve it:

```javascript
el = document.getElementsByTagName('use')[0]
el.getAttribute('xlink:href')
// "https://example/test"
```

The same thing can be done with watir-webdriver:

```ruby
browser.svg.use.attribute_value 'href'
#=> nil
browser.svg.use.attribute_value 'xlink:href'
#=> "https://example/test"
```

**Comment by bootstraponline** [comment]
Thanks for explaining.
