### ISSUE TITLE
browser.text raises NoSuchElementError if body is not present

### ISSUE THREAD

**Issue by idanci** [watir/watir-webdriver#371]
`Selenium::WebDriver::Error::NoSuchElementError: Unable to locate element: {"method":"tag name","selector":"body"}`

How do you think, is it a good idea to modify [text](https://github.com/watir/watir-webdriver/blob/6eb91b5aabcf635189efec5b1c9ae38f5e300b90/lib/watir-webdriver/browser.rb#L172) method to return empty string if `browser.body` is not present?

I navigate a lot of sites which htmls have no body, only frames and iframes and that error raises too often. 

Is there any specific reason why `browser.text` raises that error? I want to ensure if monkey patching `text` method would work for me as expected.

Regards,
Ivan

**Comment by p0deje** [comment]
I am not sure what you are trying to achieve with this, but instead of monkey-patching, why not do something like:

```ruby
browser.text if browser.body.present?
```

**Comment by idanci** [comment]
Because I have thousands calls to `browser.text` in my code. And there are hundreds cases where I catch this error. I do have places where I use `browser.text if browser.body.present?`, but I feel that something is wrong here..

**Comment by p0deje** [comment]
I'd say the current behavior of `Browser#text` is correct. Even though WebDriver does not provide anything similar, the current way of understanding text as the text of body element is valid since body is the element to contain all visible elements. The only case when this might fail is when frameset is used instead of body, but since frameset is not a part of HTML5, I don't think it makes sense to support it.

**Comment by idanci** [comment]
Thank you for your time and have a nice day ;)
