### ISSUE TITLE
Not return the final url for a redirect url in 0.9.1 any more?

### ISSUE THREAD

**Issue by wjiangjay** [watir/watir-webdriver#399]
Background: our url "/console" will do some check and redirect to the "/login" page
Just found that:

*. In version 0.8.0 will  return the final url after redirect>

```
> b.goto "https://xxxx/console"
=> "https://xxxx/login"
```

*. In version 0.9.1 will return the url of first stage "/console">

```
> b.goto "https://xxxx/console"
=> "https://xxxx/console"
```

So 
1> Do the latest version change something for the browser.goto function?
2> In future, the goto funtion will return the first stage url(seems more suitable)?

Thanks!

**Comment by Blackbaud-BretPettichord** [comment]
Can you provide a reproducible scenario?

**Comment by bret** [comment]
Can you provide a reproducible scenario?

**Comment by titusfortner** [comment]
This was changed here: https://github.com/watir/watir-webdriver/pull/369
The navigation logic itself does not contain any information about intended final url. Rather than always calling the ```browser.window.url``` method at the end of every navigation, regardless of whether the method was used to determine a redirect, it now merely returns the information that was originally passed in and requires you to explicitly call to see if the url has changed after the navigation:
```Ruby
b.goto "https://xxxx/console"  # => "https://xxxx/console"
b.window.url # => "https://xxxx/login"
```

**Comment by bret** [comment]
To me it would make more sense to return nil than to return the provided
argument. That is just confusing.

**Comment by titusfortner** [comment]
I'd be up for changing any/all of the 'procedural' methods in Watir to return nil. :)

I had this one return the uri that was constructed to maintain backward compatibility to the > 99.9% of navigation calls that don't result in a redirect, since there are no performance issues with doing that. I guess I should clarify that the 'new' behavior doesn't just return the input: 
```
b.goto 'google.com' # => 'http://google.com'
```
