### ISSUE TITLE
cause for failed browser start hidden

### ISSUE THREAD

**Issue by akostadinov** [watir/watir-webdriver#423]
Hello, there seems to be no way to figure out why browser startup failed.
```
[10] pry(#<CucuShift::DefaultWorld>)> Watir::Browser.new :firefox
Selenium::WebDriver::Error::WebDriverError: unable to obtain stable firefox connection in 60 seconds (127.0.0.1:7055)
```

The reason he I know, but this is not the case always. To replicate I just run firefox without a X11 server. But there is no indication in the backtrace that the process failed to start. I think watir could report better that process died.

**Comment by titusfortner** [comment]
Firstly, this would be a Selenium issue and not a Watir issue. Secondly, I'm not sure it would be possible to always determine why the connection doesn't happen because I know of several different causes of this error. If you have specific suggestions, please create a Selenium issue / pull request and we can take a look. Thanks.
